name: Test R Package with testthat

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'  # Use the latest stable R version

      - name: Install remotes package
        run: |
          install.packages("remotes")  # Install remotes package if it's not present

      - name: Install dependencies
        run: |
          install.packages("testthat")
          remotes::install_deps(dependencies = TRUE)  # Ensure all dependencies are installed
        shell: Rscript {0}

      - name: Install pkg-config if missing (for macOS dependencies)
        run: |
          brew install pkg-config
        shell: bash

      - name: Run tests with testthat
        run: |
          # Run testthat tests
          Rscript -e "testthat::test_dir('tests/testthat')"
        shell: Rscript {0}
