name: Test R Package with testthat

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: macOS-latest  # Running on macOS

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up R environment with the latest stable version
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install dependencies including testthat and any other necessary packages
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            testthat
            devtools

      - name: Run tests with testthat
        run: |
          testthat::test_dir("tests/testthat")  # Run the tests located in the tests/testthat directory
        shell: Rscript {0}  # Execute test script via R
