name: Test R Package with testthat

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: macOS-latest  # Running on macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Set up R environment
        with:
          r-version: 'release'  # Use the latest stable version of R

      - name: Install dependencies
        run: |
          install.packages("testthat")  # Install the testthat package
          install.packages("devtools")  # You can also install devtools if needed
        shell: Rscript {0}  # Run the installation via R

      - name: Run tests with testthat
        run: |
          Rscript -e "testthat::test_dir('tests/testthat')"  # Run the tests located in the tests/testthat directory
        shell: Rscript {0}  # Execute test script via R
